name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.10
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  notus:
    git:
      url: https://github.com/thecodebrothers/zefyr.git
      path: packages/notus
      ref: 1.0-dev
  quill_delta: 2.0.0
  html: ^0.14.0

dev_dependencies:
  test:
